spring:
  application:
    name: erply-middleware
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
        generate_statistics: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: db_user
    password: secret
    driver-class-name: org.postgresql.Driver
 
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: false

jwt.secret: jwtSecret63094f   
jwt.expirationHours: 10
authUrl: https://515669.erply.com/api
productsUrl: https://api-pim-eu.erply.com
auth:
  clientCode: 515669
  username: arturiki@gmail.com
  password: Erply1234
  sendContentType: 1